const IMAGE = {
    ICON_LOGO: require('../images/logo.svg'),
    ICON_EYE: require('../images/eye.svg'),
    ICON_EYE_ACTIVE: require('../images/eyes2.svg'),
    ICON_BACK: require('../images/back_dark.svg'),
    ICON_CLOSE: require('../images/close.svg'),
    ICON_DROPDOWN: require('../images/dropdown.svg'),
    ICON_HOME: require('../images/home.svg'),
    ICON_HOME_ACTIVE: require('../images/home_active.svg'),
    ICON_FEED: require('../images/feed.svg'),
    ICON_FEED_ACTIVE: require('../images/feed_active.svg'),
    ICON_CATEGORY: require('../images/category.svg'),
    ICON_CATEGORY_ACTIVE: require('../images/category_active.svg'),
    ICON_NOTIFICATION: require('../images/notification.svg'),
    ICON_NOTIFICATION_ACTIVE: require('../images/notification_active.svg'),
    ICON_ACCOUNT: require('../images/account.svg'),
    ICON_ACCOUNT_ACTIVE: require('../images/account_active.svg'),
    ICON_BASKET: require('../images/basket.svg'),
    ICON_SEARCH: require('../images/search.svg'),
    ICON_SCAN: require('../images/scan.svg'),
    ICON_PG_BEAUTY: require('../images/pg_beauty.svg'),
    ICON_PG_TOOL: require('../images/tool.svg'),
    ICON_PG_FASHION: require('../images/pg_fashion.svg'),
    ANH_DEMO_1: require('../images/demo1.png'),
    ANH_DEMO_2: require('../images/demo2.png'),
    ICON_STAR: require('../images/red_star.svg'),
    ICON_RECTANGLE: require('../images/Rectangle.svg'),
    ANH_DEMO_3: require('../images/anh_demo4.png'),
    TAB_BG: require('../images/tab.png'),
    TAB_ACTIVE_BG: require('../images/tab_active.png'),
    NO_NOTI: require('../images/no_noti.png'),
    BG_AVATAR: require('../images/bg_avatar.png'),
    ANH_DEMO_6: require('../images/anh_demo6.png'),
    ICON_SALE_BG: require('../images/sale_bg.png'),
    ORDER: require('../images/order.png'),
    BTN_ADD: require ('../images/btn_add.png'),
    NO_IMAGE: require('../images/no_image.png'),
    DELIVERY: require('../images/delivery.png'),
    ICON_APP: require('../images/Appicon.png'),
    FOREN_1: require('../images/foren_1.png'),
    FOREN_2: require('../images/foren_2.png'),
    FOREN_3: require('../images/foren_3.png'),
    FOREN_4: require('../images/foren_4.png'),
    FOREN_5: require('../images/foren_5.png'),
    BANNER: require('../images/banner.png')

}

export  {IMAGE}