const STRING = {
  ENTER_PHONE: 'Nhập số di động của bạn để đăng nhập',
  PH_ENTER_PHONE: 'Nhập số điện thoại',
  PH_PASSWORD: 'Mật khẩu',
  LOGIN: 'đăng nhập',
  FOGOT_PASSWORD: 'Bạn quên mật khẩu? ',
  GET_PASSWORD: 'Nhận lại mật khẩu',
  NOT_HAVE_ACCOUNT: 'Bạn chưa có tài khoản? ',
  SIGN_UP: 'Đăng kí ngay',
  FORGOT_PASSWORD_TITLE: 'Quên mật khẩu',
  SUBMESS1: 'Vui lòng nhập ',
  SUBMESS2: ' của bạn đã đăng ký để nhận mật khẩu mới',
  EMAIL_PHONE: 'Email / Số điện thoại',
  SEND_PASSWORD: 'gửi lại mật khẩu',
  ENTER_INFO: 'Nhập thông tin của bạn để đăng ký tài khoản',
  ENTER_NAME: 'Họ và tên *',
  ENTER_DATE_OF_BIRTH: 'Năm sinh',
  ENTER_ADDRESS: 'Địa chỉ',
  EMAIL: 'Email',
  ENTER_PHONE_INPUT: 'Số điện thoại *',
  ENTER_PASSWORD: 'Mật khẩu *',
  CONFIRM_PASSWORD: 'Xác nhận lại mật khẩu *',
  REGISTER: 'đăng kí',
  HAVE_ACCOUNT: 'Bạn đã có tài khoản? ',
  LOGIN_NOW: 'Đăng nhập ngay!',
  DEAL_NOW: 'deal đang diễn ra',
  SEE_ALL: 'Xem tất cả',
  SELLING_PRODUCT: 'sản phẩm bán chạy',
  SEARCH_INPUT: 'Tìm kiếm: son, máy rửa mặt...',
  NEW_PRODUCT: 'sản phẩm mới',
  PG_BEAUTY_FEED: 'PG Beauty Feed',
  POSTS_LIKE: 'Bài viết nhiều người thích',
  POSTS_REVIEW: 'Bài viết nhiều người đánh giá',
  VIEWS: 'Lượt xem',
  SOLD: 'Đã bán',
  PG_BEAUTY: 'PG Beauty',
  PG_BEAUTY_TOOL: 'PG Beauty tool',
  PG_FASHION: 'PG Fashion',
  LIKE: 'Thích',
  COMMENT_1: 'Bình luận',
  COMMENT_2: 'bình luận',
  SHARE: 'Chia sẻ',
  CLEANSING: 'Tẩy trang',
  CLEANSER: 'Sữa rửa mặt',
  NOTIFICATION: 'Thông báo',
  PROMOTION: 'Khuyến mãi',
  FOR_YOU: 'Của bạn',
  NO_NOTI: 'Hiện chưa có thông báo nào của bạn',
  PRODUCTS_PURCHASED: 'sản phẩm đã mua',
  REWARD_POINT: 'Điểm thưởng',
  D: 'đ',
  PURCHASED_HISTORY: 'Lịch sử mua hàng',
  MY_RATE: 'Đánh giá của tôi',
  SETTING: 'Cài đặt',
  INFO: 'Thông tin về PG Beauty',
  USE_GUIDE: 'Hướng dẫn sử dụng app',
  SHOPPING_GUIDE: 'Hướng dẫn mua hàng',
  PAYMENT_POLICY: 'Chính sách thanh toán',
  POLICY_DELIVERY: 'Chính sách giao nhận - vận chuyển',
  RETURN_POLICY: 'Chính sách đổi hàng',
  TERM_OF_USE_POLICY: 'Chính sách điều khoản sử dụng',
  SHOPS: 'Hệ thống cửa hàng',
  INTRODUCE_PG_BEAUTY: 'Giới thiệu PG Beauty',
  VERSION: 'Verson cập nhật mới nhất',
  SEND: 'Gửi',
  WRITE_COMMENT: 'Viết bình luận',
  COLOR: 'Màu sắc:',
  AVAILABLE: 'còn hàng',
  OUT_OF_STOCK: 'hết hàng',
  AMOUNT: 'Số lượng',
  STILL: 'còn',
  DELIVERY: 'Giao hàng',
  DESCRIPTION: 'Mô tả sản phẩm',
  PRODUCT_SPECIFICATION: 'Thông số sản phẩm',
  TRADE_MARK: 'Thương hiệu',
  MADE_IN: 'Xuất xứ',
  SPECIES: 'Loại',
  SAME_PRODUCT: 'Sản phẩm cùng loại',
  SAME_TRADE_MARK: 'Sản phẩm cùng thương hiệu',
  CART: 'Giỏ hàng',
  CANCEL: 'Huỷ',
  LOGIN_INFO: 'Để trải nghiệm những ưu đãi độc quyền của bạn tại PG Beauty',
  ENTER_DISCOUNT_CODE: 'Nhập mã giảm giá (nếu có)',
  LOGOUT: 'Đăng xuất',
  APPLY: 'áp dụng',
  DISCOUNT_LEVEL: 'Mức giảm',
  MONEY: 'Tiền hàng',
  DISCOUNT: 'Giảm giá',
  TOTAL: 'Tổng thanh toán',
  CONTINUE: 'tiếp tục',
  ORDER_INFO: 'Thông tin đặt hàng',
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
  PAY: 'Thanh toán',
  DONE: 'Hoàn thành',
  PHONE: 'Số điện thoại *',
  CITY: 'Tỉnh/ thành phố *',
  DISTRICT: 'Quận/Huyện *',
  WARD: 'Phường/Xã *',
  ADDRESS: 'Địa chỉ *',
  NOTE_ORDER: 'Viết lưu ý cho người bán / giao hàng',
  SHIPPING_ADDRESS: 'Địa chỉ nhận hàng',
  NOTE: 'Ghi chú: ',
  TRANSPORTATION: 'Hình thức vận chuyển',
  PAYMENT_METHOD: 'Phương thức thanh toán',
  ORDER: 'đặt hàng',
  NOTIFI: 'Thông báo',
  ACCEPT: 'Đồng ý',
  SIGN_UP_SUCCESS: 'Đăng kí thành công!',
  ERROR: 'Lỗi',
  REQUIRED_FIELD: 'Các trường có dấu (*) không được bỏ trống!',
  ERR_CONFIRM_PASS: 'Xác nhận mật khẩu không chính xác, kiểm tra lại!',
  LESS_THAN_8: 'Mật khẩu không được nhỏ hơn 8 kí tự, kiểm tra lại!',
  ERR_NULL_PHONE_PASS: 'Số điện thoại và mật khẩu không được bỏ trống!',
  CURRENCY: 'đ',
  VIEW_MORE: 'Xem thêm',
  FONT_NORMAL: 'Nunito-Regular',
  FONT_BOLD: 'Nunito-Bold',
  FONT_SEMI_BOLD: 'Nunito-SemiBold',
  TAG: '#',
  WARNING: 'Cảnh báo',
  LOGIN_BEFORE_ORDER: 'Bạn cần đăng nhập trước khi đặt hàng',
  CHOOSE_QUANTITY: 'Vui lòng chọn số lượng',
  ORDER_FAILED: 'Đặt hàng thất bại, hãy thử lại!',
  ORDER_SUCCESS: 'Đặt hàng thành công!',
  REGISTRATION_FAILED: 'Đăng kí thất bại, hãy thử lại',
  NO_ORDER: 'Hiện chưa có đơn hàng nào',
  HISTORY: 'Lịch sử mua hàng',
  BUY_ONLINE: 'Mua Online',
  BUY_AT_STORE: 'Mua tại cửa hàng',
  ALL: 'Tất cả',
  NEW_ORDER: 'Mới đặt',
  PROCESSING: 'Đang xử lí',
  SUCCESS: 'Thành công',
  CANCELED: 'Đã hủy',
  LOGIN_FAILED: 'Đăng nhập thất bại',
  DETAIL_ORDER: 'Chi tiết đơn hàng',
  LIST_PRODUCTS: 'Danh sách sản phẩm',
  AT: 'lúc',
  STATUS: 'Trạng thái',
  SUGGEST: 'Gợi ý',
  SEARCH_HISTORY: 'Lịch sử tìm kiếm',
  DELETE_HISTORY: 'Xóa lịch sử',
  FEW_SECOND_AGO: 'Vài giây trước',
  MINUTES_AGO: ' phút trước',
  HOURS_AGO: ' giờ trước',
  MUST_LOGIN_TO_LIKE_AND_COMMENT:
    'Bạn cần đăng nhập để có thể thích và bình luận bài viết!',
  SEARCH_RESULT: 'Kết quả tìm kiếm',
  ACTIVE_GUARANTEE_FOREO: 'HƯỚNG DẪN ACTIVE VÀ BẢO HÀNH FOREO',
  INTRO_FOREO:
    'Máy rửa mặt FOREO LUNA 3 VÀ MINI 3, cần được active và đăng kí bảo hành qua Foreo App cho lần đầu tiên. Sau đó khi dùng máy chỉ cần bật nút nguồn và sử dụng.',
  STEP_1:
    'B1: Đầu tiên các bạn down “FOREO FOR YOU” app về máy điện thoại của bạn. Lưu ý máy điện thoại IOS 12.0 trở lên và Adroid từ 6.0 trở lên.',
  STEP_2: 'B2: Tạo tài khoản Foreo',
  STEP_2_DETAIL:
    '>>>TRƯỜNG HỢP 1: NẾU BẠN ĐÃ LẬP TÀI KHOẢN FOREO TRƯỚC ĐÓ RỒI, Bạn chỉ cần đăng nhập vào bằng cách điền thông tin như chỉ dẫn: Email + Password + ấn LOG IN >>>TRƯỜNG HỢP 2: NẾU BẠN CHƯA CÓ TK FOREO, bạn click vào "Create Account" để tạo tài khoản - Các bước tạo tài khoản mới ở bước tiếp theo ',
  STEP_2_1: '1. Điền hết các thông tin ở bước tạo tài khoản',
  STEP_2_2: '2. Ấn “Got it” để Foreo gửi mã kích hoạt Tk vào email của bạn',
  STEP_2_3:
    '3. Mở email sẽ thấy thư của Foreo gửi mã kích hoạt, gồm 4 số và nhập vào. ',
  STEP_2_4: '4. Chọn các model để active và đăng kí bảo hành.',
  STEP_3: 'B3: ACTIVE VÀ ĐĂNG KÍ BẢO HÀNH CHO MÁY.',
  STEP_3_1:
    '5. Bạn sẽ ấn và giữ vào nút nguồn 5s (Bạn nên giữ lâu hơn 5s, không nên ấn vào rồi bỏ tay ra luôn, để cho tới khi màn hình hiện lên thông tin về máy là được). ',
  STEP_3_2:
    '6. Đăng kí bảo hành: bạn điền các thông tin: “Purchase Date – ngày mua – chọn ngày bạn kích hoạt máy. Upload proof of purchase – bạn không cần điền. Where did you buy your product –nơi mua hàng - bạn chọn “Duty Free”. Sau đó ấn “REGISTER DEVICE”.',
  STEP_4: 'B4: Cài đặt chế độ cho máy',
  STEP_4_1:
    '7. Chế độ dùng thử của hãng, họ cài mức rung 8 và time 60s. Nhưng mức rung này khá mạnh, các bạn sẽ cài đặt lại chế độ nhé.',
  STEP_4_2: '8. Cài chế độ: bạn chọn nút setting hình bánh răng.',
  STEP_4_3:
    '9. Intensity “mức rung”, bạn nên chọn 5-6 là mức thông thường, người nào mới sử dụng thì lên dùng 3-4 sau đó có thể tăng dần lên. Time = 60s là thời gian tiêu chuẩn tốt nhất cho 1 lần rửa mặt.',
  STEP_4_4:
    '10. Sử dụng chế độ glow, bạn chọn sang glow, chế độ này mặc đinh mức rung là 16, và time chỉ 30s. Không nên sử dụng nhiều mức này, chỉ lên 1 tuần dung 2-3 lần',
  FOREO_AFTER_ACTIVE:
    '- Sau khi ACTIVE VÀ ĐĂNG KÍ BẢO HÀNH xong, bạn thoát App ra và bật nút nguồn sử dụng khi cần rửa mặt. Máy rửa mặt sẽ chạy theo chu trình bạn đã cài đặt. Khi bạn muốn sử dụng chế độ glow cho mini 3, bạn chỉ cần mở máy, sau đó ấn 2 lần liên tiếp nút nguồn là được. Khi máy chạy ở chế độ “GLOW BOOSTE” Máy sẽ nháy và sáng đèn ở dưới, chạy ở mức 16 và 30s sẽ dừng lại.',
  FOREO_NOTE:
    '- Note: trường hợp khi đang kí màn hình thông báo lỗi, bạn chỉ cần thoát App ra và đăng nhập lại là được nhé. Khi cài xong và không cần sử dụng tới App thì nên thoát App ra để khỏi bị lỗi khi App nâng cấp',
  LUNA_3: 'ĐỐI VỚI LUNA 3: (KHI SỬ DỤNG CHẾ ĐỘ MASSAGE)',
  LUNA_3_1:
    '- Luna 3 có thêm chức năng massage, và được hãng cài đặt chế độ massge, hướng dẫn cách massge chi tiết trong APP. Khi sử dụng muốn sử dụng chế độ massge.',
  LUNA_3_2:
    '- Bạn đăng nhập Tk vào, Click nút “3”-(START) – Bạn sẽ click dòng chữ “15”- Go to massage treatments”. Và sẽ làm massage theo các vùng như hướng dẫn nha.',
  LUNA_2: 'ĐỐI VỚI LUNA MINI 2',
  LUNA_2_1:
    '- Đối với mini 2, thì bạn vẫn làm bước tạo tài khoản như trên, còn bước đăng kí bảo hành, bạn chọn đúng model và nhập serial number vào và ấn đăng kí là được nhé',
  LUNA_2_2:
    '- Đăng kí mini 2, Bạn chọn model máy mini 2, và màn hình sẽ hiện ra như sau.',
  LUNA_2_3: 'Cách 1: Bạn sẽ scan seri number dưới đấy máy, bắt đầu bằng chữ F',
  LUNA_2_4: 'Cách 2: Bạn có thể nhập seri number',
  LUNA_2_5: 'Sau đó ấn verify device là đăng kí thành công máy mini 2 nhé.',
  TOTAL_NOT_YET_SHIP: '(*Tổng thanh toán chưa bao gồm phí giao hàng)',
  CHANGE_ADDRESS: 'Thay đổi địa chỉ',
  CODE_PUSH_ANDROID:
    'appcenter codepush release-react -a khanhnd241/Android-PGBeautyApp -d Production',
  CODE_PUSH_IOS:
    'appcenter codepush release-react -a khanhnd241/IOS-PGBeautyApp -d Production',
};

export {STRING};
