const STRING = {
    ENTER_PHONE:'Nhập số di động của bạn để đăng nhập',
    PH_ENTER_PHONE: "Nhập số điện thoại",
    PH_PASSWORD: "Mật khẩu",
    LOGIN:'đăng nhập',
    FOGOT_PASSWORD: 'Bạn quên mật khẩu? ',
    GET_PASSWORD: 'Nhận lại mật khẩu',
    NOT_HAVE_ACCOUNT: 'Bạn chưa có tài khoản? ',
    SIGN_UP: 'Đăng kí ngay',
    FORGOT_PASSWORD_TITLE: 'Quên mật khẩu',
    SUBMESS1: 'Vui lòng nhập ',
    SUBMESS2: ' của bạn đã đăng ký để nhận mật khẩu mới',
    EMAIL_PHONE: 'Email / Số điện thoại',
    SEND_PASSWORD: 'gửi lại mật khẩu',
    ENTER_INFO: 'Nhập thông tin của bạn để đăng ký tài khoản',
    ENTER_NAME: 'Họ và tên *',
    ENTER_DATE_OF_BIRTH: 'Năm sinh',
    ENTER_ADDRESS: 'Địa chỉ',
    EMAIL: 'Email',
    ENTER_PHONE_INPUT: 'Số điện thoại *',
    ENTER_PASSWORD: 'Mật khẩu *',
    CONFIRM_PASSWORD: 'Xác nhận lại mật khẩu *',
    REGISTER: 'đăng kí',
    HAVE_ACCOUNT: 'Bạn đã có tài khoản? ',
    LOGIN_NOW: 'Đăng nhập ngay!',
    DEAL_NOW: 'deal đang diễn ra',
    SEE_ALL: 'Xem tất cả',
    SELLING_PRODUCT: 'sản phẩm bán chạy',
    SEARCH_INPUT: 'Tìm kiếm: son, máy rửa mặt...',
    NEW_PRODUCT: 'sản phẩm mới',
    PG_BEAUTY_FEED: 'PG Beauty Feed',
    POSTS_LIKE: 'Bài viết nhiều người thích',
    POSTS_REVIEW: 'Bài viết nhiều người đánh giá',
    REVIEW: 'review',
    SOLD: 'Đã bán',
    PG_BEAUTY: 'PG Beauty',
    PG_BEAUTY_TOOL: 'PG Beauty tool',
    PG_FASHION: 'PG Fashion',
    LIKE: 'Thích',
    COMMENT_1: 'Bình luận',
    COMMENT_2: 'bình luận',
    SHARE: 'Chia sẻ',
    CLEANSING: 'Tẩy trang',
    CLEANSER: 'Sữa rửa mặt',
    NOTIFICATION: 'Thông báo',
    PROMOTION: 'Khuyến mãi',
    FOR_YOU: 'Của bạn',
    NO_NOTI: 'Hiện chưa có thông báo nào của bạn',
    PRODUCTS_PURCHASED: 'sản phẩm đã mua',
    REWARD_POINT: 'Điểm thưởng',
    D: 'đ',
    PURCHASED_HISTORY: 'Lịch sử mua hàng',
    MY_RATE: 'Đánh giá của tôi',
    SETTING: 'Cài đặt',
    INFO: 'Thông tin về PG Beauty',
    USE_GUIDE: 'Hướng dẫn sử dụng app',
    SHOPPING_GUIDE: 'Hướng dẫn mua hàng',
    PAYMENT_POLICY: 'Chính sách thanh toán',
    POLICY_DELIVERY: 'Chính sách giao nhận - vận chuyển',
    RETURN_POLICY: 'Chính sách đổi hàng',
    TERM_OF_USE_POLICY: 'Chính sách điều khoản sử dụng',
    SHOPS: 'Hệ thống cửa hàng',
    INTRODUCE_PG_BEAUTY: 'Giới thiệu PG Beauty',
    VERSION: 'Verson cập nhật mới nhất',
    SEND: 'Gửi',
    WRITE_COMMENT: 'Viết bình luận',
    COLOR: 'Màu sắc:',
    AVAILABLE: 'còn hàng',
    OUT_OF_STOCK: 'hết hàng',
    AMOUNT: 'Số lượng',
    STILL: 'còn',
    DELIVERY: 'Giao hàng',
    DESCRIPTION: 'Mô tả sản phẩm',
    PRODUCT_SPECIFICATION: 'Thông số sản phẩm',
    TRADE_MARK: 'Thương hiệu',
    MADE_IN: 'Xuất xứ',
    SPECIES: 'Loại',
    SAME_PRODUCT: 'Sản phẩm cùng loại',
    SAME_TRADE_MARK: 'Sản phẩm cùng thương hiệu',
    CART: 'Giỏ hàng',
    CANCEL: 'Huỷ',
    LOGIN_INFO: 'Để trải nghiệm những ưu đãi độc quyền của bạn tại PG Beauty',
    ENTER_DISCOUNT_CODE: 'Nhập mã giảm giá (nếu có)',
    LOGOUT: 'Đăng xuất',
    APPLY: 'áp dụng',
    DISCOUNT_LEVEL: 'Mức giảm',
    MONEY: 'Tiền hàng',
    DISCOUNT: 'Giảm giá',
    TOTAL: 'Tổng thanh toán',
    CONTINUE: 'tiếp tục',
    ORDER_INFO: 'Thông tin đặt hàng',
    NUMBER_1: '1',
    NUMBER_2: '2',
    NUMBER_3: '3',
    PAY: 'Thanh toán',
    DONE: 'Hoàn thành',
    PHONE: 'Số điện thoại *',
    CITY: 'Tỉnh/ thành phố *',
    DISTRICT: 'Quận/Huyện *',
    WARD: 'Phường/Xã *',
    ADDRESS: 'Địa chỉ *',
    NOTE_ORDER: 'Viết lưu ý cho người bán / giao hàng',
    SHIPPING_ADDRESS: 'Địa chỉ nhận hàng',
    NOTE: 'Ghi chú: ',
    TRANSPORTATION: 'Hình thức vận chuyển',
    PAYMENT_METHOD: 'Phương thức thanh toán',
    ORDER: 'đặt hàng',
    NOTIFI: 'Thông báo',
    ACCEPT: 'Đồng ý',
    SIGN_UP_SUCCESS: 'Đăng kí thành công!',
    ERROR: 'Lỗi',
    REQUIRED_FIELD: 'Các trường có dấu (*) không được bỏ trống!',
    ERR_CONFIRM_PASS: 'Xác nhận mật khẩu không chính xác, kiểm tra lại!',
    LESS_THAN_8: 'Mật khẩu không được nhỏ hơn 8 kí tự, kiểm tra lại!',
    ERR_NULL_PHONE_PASS: 'Số điện thoại và mật khẩu không được bỏ trống!',
    CURRENCY: 'đ',
    VIEW_MORE: 'Xem thêm',
    FONT_NORMAL: 'Nunito-Regular',
    TAG: '#'
}

export  {STRING}