const STRING = {
    ENTER_PHONE:'Nhập số di động của bạn để đăng nhập',
    PH_ENTER_PHONE: "Nhập số điện thoại",
    PH_PASSWORD: "Mật khẩu",
    LOGIN:'đăng nhập',
    FOGOT_PASSWORD: 'Bạn quên mật khẩu? ',
    GET_PASSWORD: 'Nhận lại mật khẩu',
    NOT_HAVE_ACCOUNT: 'Bạn chưa có tài khoản? ',
    SIGN_UP: 'Đăng kí ngay',
    FORGOT_PASSWORD_TITLE: 'Quên mật khẩu',
    SUBMESS1: 'Vui lòng nhập ',
    SUBMESS2: ' của bạn đã đăng ký để nhận mật khẩu mới',
    EMAIL_PHONE: 'Email / Số điện thoại',
    SEND_PASSWORD: 'gửi lại mật khẩu',
    ENTER_INFO: 'Nhập thông tin của bạn để đăng ký tài khoản',
    ENTER_NAME: 'Họ và tên *',
    ENTER_DATE_OF_BIRTH: 'Năm sinh',
    ENTER_ADDRESS: 'Địa chỉ',
    EMAIL: 'Email',
    ENTER_PHONE_INPUT: 'Số điện thoại *',
    ENTER_PASSWORD: 'Mật khẩu *',
    CONFIRM_PASSWORD: 'Xác nhận lại mật khẩu *',
    REGISTER: 'đăng kí',
    HAVE_ACCOUNT: 'Bạn đã có tài khoản? ',
    LOGIN_NOW: 'Đăng nhập ngay!',
    DEAL_NOW: 'deal đang diễn ra',
    SEE_ALL: 'Xem tất cả',
    SELLING_PRODUCT: 'sản phẩm bán chạy',
    SEARCH_INPUT: 'Tìm kiếm: son, máy rửa mặt...',
    NEW_PRODUCT: 'sản phẩm mới',
    PG_BEAUTY_FEED: 'PG Beauty Feed',
    POSTS_LIKE: 'Bài viết nhiều người thích',
    POSTS_REVIEW: 'Bài viết nhiều người đánh giá',
    REVIEW: 'review',
    SOLD: 'Đã bán',
    PG_BEAUTY: 'PG Beauty',
    PG_BEAUTY_TOOL: 'PG Beauty tool',
    PG_FASHION: 'PG Fashion',
    LIKE: 'Thích',
    COMMENT_1: 'Bình luận',
    COMMENT_2: 'bình luận',
    SHARE: 'Chia sẻ',
    CLEANSING: 'Tẩy trang',
    CLEANSER: 'Sữa rửa mặt',
    NOTIFICATION: 'Thông báo',
    PROMOTION: 'Khuyến mãi',
    FOR_YOU: 'Của bạn',
    NO_NOTI: 'Hiện chưa có thông báo nào của bạn',
    PRODUCTS_PURCHASED: 'sản phẩm đã mua',
    REWARD_POINT: 'Điểm thưởng',
    D: 'đ',
    PURCHASED_HISTORY: 'Lịch sử mua hàng',
    MY_RATE: 'Đánh giá của tôi',
    SETTING: 'Cài đặt',
    INFO: 'Thông tin về PG Beauty',
    USE_GUIDE: 'Hướng dẫn sử dụng app',
    SHOPPING_GUIDE: 'Hướng dẫn mua hàng',
    PAYMENT_POLICY: 'Chính sách thanh toán',
    POLICY_DELIVERY: 'Chính sách giao nhận - vận chuyển',
    RETURN_POLICY: 'Chính sách đổi hàng',
    TERM_OF_USE_POLICY: 'Chính sách điều khoản sử dụng',
    SHOPS: 'Hệ thống cửa hàng',
    INTRODUCE_PG_BEAUTY: 'Giới thiệu PG Beauty',
    VERSION: 'Verson cập nhật mới nhất'
}

export  {STRING}